name: Release Build

on:
  push:
    tags:
      - "v*"

permissions: read-all
jobs:
  container:
    name: Build container image
    uses: ./.github/workflows/container-image.yaml
    permissions:
      id-token: write
      packages: write
    with:
      push-image: true

